### ISSUE TITLE
[Site/Xooxle] Your Definition of Word Boundary doesn't Match Chrome's

### ISSUE THREAD

**Issue by pishoyg** [pishoyg/coptic#286]
Your extracted text fragments are not always understood by browser. You might want to revisit [this method](https://github.com/pishoyg/coptic/blob/30ac92180bee1e46671ef226f4974f844f8745af/site/xooxle.ts#L309-L331), which is specifically written to generate text fragments for browser highlighting.

**Comment by remnqymi** [comment]
The apostrophe seems to be correctly interpreted by Chrome as a word character. Only Safari still has this issue.

**Comment by pishoyg** [comment]
Here is a broken link produced by Xooxle: https://remnqymi.com/crum/212.html#:~:text=s%20mouth%20full%20of-,smeared%20with,-(prob)%5B1%5D%20%CF%AB%E2%B2%93%CF%A9%20%CF%A9%E2%B2%93%E2%B2%89%E2%B2%93

This works: https://remnqymi.com/crum/212.html#:~:text=mouth%20full%20of-,smeared%20with,-(prob)%5B1%5D%20%CF%AB%E2%B2%93%CF%A9%20%CF%A9%E2%B2%93%E2%B2%89%E2%B2%93

This too:
https://remnqymi.com/crum/212.html#:~:text=babe's%20mouth%20full%20of-,smeared%20with,-(prob)%5B1%5D%20%CF%AB%E2%B2%93%CF%A9%20%CF%A9%E2%B2%93%E2%B2%89%E2%B2%93

**Comment by remnqymi** [comment]
This link is also broken: http://remnqymi.com/crum/1153.html#:~:text=B%20%E2%B2%A3%E2%B2%B1%E2%B2%95%CF%A9)%20%CE%B5%CE%BA%CE%BA%CE%B1%CE%B9.%20%CE%B5%CE%B9%CF%82%2C-,ShA2%20279,-ShA%202%20279%E2%80%A1%20God
